Second Milestone
userman95/bookstore pull request #2
Opened 2019-10-05 17:33 UTC by userman95

2019-10-07 10:48 UTC, BalintMendli requested changes
Hi @userman95 ,

Great job in this milestone. 👏 

Please read my comments below and make the appropriate changes.

Also let's set up all import and exports properly and make sure the application works.

When done please submit a review request.

If you have any questions reach out to me on Slack.

2019-10-07 10:48 UTC, zenott commented on src/containers/BooksForm.js
> +                <option value="category">{category}</option>
Lists in react need to have a unique `key` property in order to identify them for performance reasons. See the [docs](https://reactjs.org/docs/lists-and-keys.html#keys). 
So let's add a `key` prop to the mapped component.

2019-10-07 10:48 UTC, zenott commented on src/containers/BooksList.js
> +                    <Book />
Let's add a `key` property here as well.

2019-10-08 09:44 UTC, SunnyAsar approved these changes
# Hi @userman95 😃 
### update Looks good! please proceed 🚀 

## You May Pass 👍

2019-10-08 13:14 UTC, merged