Third milsestone
userman95/bookstore pull request #4
Opened 2019-10-08 03:30 UTC by userman95

2019-10-08 10:10 UTC, SunnyAsar requested changes
# Hi @userman95  Nice job 
But: - Why are you working alone on this project?

### There are few things we need to address to make this milestone complete.
- see the comment for the updated needed.
- please always add a summary of what you have done in the pull request description
- Please stop ignoring the linting rules, you have alot of linting errors in files across the project:
![Screenshot 2019-10-08 at 11 06 16 AM](https://user-images.githubusercontent.com/10922508/66387543-1069bf80-e9bc-11e9-9676-43db6ff3555b.png)

** Please make the updates and request another review**
 Happy Coding.

2019-10-08 10:10 UTC, SunnyAsar commented on src/containers/BooksForm.js
> +          category: '',
Hey, by default. category should be the first item in  `bookCategories ` else this happens:
![Screenshot 2019-10-08 at 10 54 53 AM](https://user-images.githubusercontent.com/10922508/66386581-60478700-e9ba-11e9-94f1-d2fe94299ad1.png)

- look at the last entry there is no category because as the app is started i didn't pick a category.

2019-10-08 10:10 UTC, SunnyAsar commented on src/containers/BooksForm.js
> +        this.setState({ title: '',category: '' });
Also after creation let's set the category back to 'Action' again

2019-10-08 10:10 UTC, SunnyAsar commented on src/containers/BooksForm.js
> +        event.preventDefault();
This file is not properly formatted, the indentation and spacing between methods, not correct. 
Please fix

2019-10-08 13:39 UTC, userman95 commented
Hey Sunny. I am working alone because there is no student in the same path that i am right now and my coding parthner is in the todolist project , so he is very far behind me . I don't have much work left so i will do this alone . Ok for the linting errors , i thought that sticler will fix them but it seems like it doesn't .

2019-10-08 13:40 UTC, userman95 commented on src/containers/BooksForm.js
> +          category: '',
yeah youa re right! Thanks will fix 👍

2019-10-09 07:57 UTC, BalintMendli requested changes
Hi @userman95 ,

We have a bug. 🐛 

I get this error when I try to add a new book:

![Capture](https://user-images.githubusercontent.com/35330692/66460856-16bd7180-ea78-11e9-8f11-f42643fac836.JPG)

Something's not set up right in the createBook action. Please fix it.

If you happen to need help with it just hit me up on Slack.

When working please submit another review request.

2019-10-09 07:57 UTC, zenott commented on src/containers/BooksForm.js
> +        <select id="category" onChange={this.handleChange}>
Let's make the select element controlled as well. Add `value={category}` prop to it to update based on the state.

2019-10-09 07:57 UTC, zenott commented on src/containers/BooksForm.js
> +    document.getElementById(bookCategories[0]).selected = true;
We don't need this if we make the select controlled. See my next comment.

2019-10-10 07:14 UTC, BalintMendli approved these changes
Hi @userman95 ,

All good for the milestone.

### 👍

2019-10-10 13:59 UTC, merged